format = """\
$time\
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$character\
"""

add_newline = false

[time]
disabled = false
format = '[$time](yellow)'
time_format = "%Y-%m-%d "

[username]
disabled = false
format = '[$user](bold cyan)'
show_always = true

[hostname]
disabled = false
format = '[@$hostname](bold cyan) '
ssh_only = false

[directory]
disabled = false
truncation_length = 0
truncate_to_repo = false
format = '[$path](bold green) '

[git_branch]
disabled = false
always_show_remote = true
format = '[$branch](yellow)'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]](red) )'

[character]
disabled = false
format = '[\$](white) '

[custom.os]
disabled = false
command = 'source /etc/os-release && echo "${ID}-${VERSION_ID}"'
format = '[$output](white) '
shell = ['bash', '-c']
when = true
