format = """\
$time\
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$character\
"""

[time]
disabled = true
format = '[$time](bold yellow)'
time_format = "%Y-%m-%d %a %H:%M:%S "

[username]
disabled = false
format = '[$user](bold cyan)'
show_always = true

[hostname]
disabled = false
format = '[@$hostname](bold cyan) '
ssh_only = false

[directory]
disabled = false
format = '[$path](bold green) '
truncate_to_repo = false
truncation_length = 0

[git_branch]
disabled = false
always_show_remote = true
format = '[$branch](bold yellow)'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]](bold red) )'

[character]
disabled = false
format = '[$symbol](green) '
success_symbol = '[\$](bold white)'
error_symbol =  '[\$](bold red)'
