context.modules = [
    { name = libpipewire-module-loopback
        args = {
            node.description = "Mono Audio Device"
            capture.props = {
                audio.position = [ MONO ]
                media.class    = "Audio/Sink"
                node.name      = "mono_output"
            }
            playback.props = {
                audio.position = [ MONO ]
                node.name      = "playback.mono_output"
                node.passive   = true
            }
        }
    }
]
