// $ cat 99-slim-apt.conf

// disable ipv6
Acquire::ForceIPv4 "true";

// disable package sources
Acquire::IndexTargets::deb-src::Packages::DefaultEnabled "false";

// disable metadata
Acquire::IndexTargets::deb::Contents-deb::DefaultEnabled "false";

// disable translations
Acquire::IndexTargets::deb::Translations::DefaultEnabled "false";

// disable other languages
Acquire::Languages "none";

// disable recommended pacakges
APT::Install-Recommends "false";

// disable suggested packages
APT::Install-Suggests "false";

// disable package cache
APT::Keep-Downloaded-Packages "false";
