"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character\
"""

[custom.windows]
disabled = true
command = '(Get-CIMInstance -ClassName Win32_OperatingSystem).Caption.Replace(" ", "-").ToLower() + "-" + (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\").CurrentBuild'
format = '[($output)](dimmed white) '
shell = ['powershell', '-command']
use_stdin = false
when = true

[custom.linux]
disabled = true
command = 'source /etc/os-release && echo "${ID}-${VERSION_ID}"'
format = '[($output)](dimmed white) '
shell = ['bash', '-c']
use_stdin = false
when = true

[custom.ssh]
disabled = true
command = '[[ -n "${SSH_TTY}" ]] && echo ssh'
format = '[$output](dimmed white)'
shell = ['bash', '-c']
use_stdin = false
when = true

[time]
disabled = false
format = '[$time](dimmed white) '
time_format = '%Y-%m-%d %a %H:%M:%S'

[username]
disabled = false
format = '[$user](bold bright-green)'
show_always = true

[hostname]
disabled = false
format = '[@$hostname](bold bright-green) '
ssh_only = false

[directory]
disabled = false
format = '[$path](bold bright-cyan) '
truncate_to_repo = false
truncation_length = 0

[git_branch]
disabled = false
always_show_remote = true
format = '[$branch](bold bright-yellow) '

[git_status]
disabled = false
format = '[$all_status$ahead_behind](bold bright-red) '

[character]
disabled = false
# success_symbol = '[λ](bold dimmed white)'
# error_symbol =  '[λ](bold dimmed red)'
success_symbol = '[\$](green)'
error_symbol =  '[\$](red)'
